### ISSUE TITLE
[提案] 記述量削減その3.1

### ISSUE THREAD

**Issue by lolita-is-godddd** [jaoafa/MyMaid2#16]
## Issue Type (Issueの種別)
- [ ] バグ報告
- [ ] 新機能提案
- [x] 既存機能の強化
- [ ] 疑問

## Description (概要)
(細かいけど単に`Player`って書くとすっきりすると思う)
## Source code etc (ソースコードなど)
https://github.com/jaoafa/MyMaid2/blob/master/src/main/java/com/jaoafa/MyMaid2/Command/Cmd_DelHome.java のL.67
## Steps to Reproduce (再現の手順)
なし
## ScreenShot etc (スクリーンショットなど)
なし
## Related files (関連するファイル)
なし

**Comment by book000** [comment]
MyMaid無印のときにPlayer.javaというファイルを作っちゃったせいで明確に書いてたために発生したものですね…直します
